### ISSUE TITLE
Update of java library 2.5.1 to 2.6.4

### ISSUE THREAD

**Issue by Maudboomen** [2gplus/mendix-applicationinsights#1]
Dear Sir / Madam, 

We saw there is an update on the java library file "applicationinsights-web/2.5.1". The new version is 2.6.4.
Could you please update the module? 

Thank you in advance, 

Kind regards, 

Maud van den Boomen

**Comment by pgussow** [comment]
I've uploaded a new version with the updated jar!

**Comment by Maudboomen** [comment]
Dear Sir / Madam, 

Thank you for the update. 
Is it right that the module is not in the Mendix Marketplace yet? 

Thank you in advance. 

Kinder regards, 

Maud van den Boomen

**Comment by pgussow** [comment]
Hi Maud,

There were problems with the draft in the Mendix app store. Mendix changed the number of screenshots allowed, but there was no way to remove them. They resolved this today, so I was able to publish the new version.

Regards,
Phillip
